### ISSUE TITLE
Making SelectedKey parameter two-way binding in BitNav component

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#590] opened 2021-07-13 22:43 UTC
It is better to make the SelectedKey parameter two-way binding so that the consumer can change the amount according to his needs while running the program

**Comment by msynk** [comment] 2021-07-15 15:13
duplicate of #478 
I'm closing it due to the same reason.

**Closed by msynk** 2021-07-15 15:13 UTC
